# Generated by Django 3.2.7 on 2021-10-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=32)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Autor',
            new_name='Autores',
        ),
        migrations.AlterModelOptions(
            name='autores',
            options={'verbose_name_plural': 'autores'},
        ),
    ]
