# Generated by Django 3.2.7 on 2021-10-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_autores_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.editora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.CharField(default=0.0, max_length=32),
            preserve_default=False,
        ),
    ]
