# Generated by Django 3.2.7 on 2021-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itenscompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscompra',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.FloatField(),
        ),
    ]
